o
Bulgakoff/BaseDjango pull request #3
Opened 2020-12-08 12:15 UTC by Bulgakoff

2020-12-09 13:35 UTC, Bulgakoff commented
ЗАГЛУШКА СДАМ БЛИЖЕ К ПН

2020-12-10 06:55 UTC, Bulgakoff commented
Скинул для проверки  вариант 3 го задания

2020-12-10 09:30 UTC, Vokler requested changes
Удалите так же из проекта `__pycahce__` и папку media - они для локальной работы только.

2020-12-10 09:30 UTC, Vokler commented on .gitignore
> +.idea/
Слэш не нужен для данной папки (она находится только в корне). А слэш нужен чтобы все файлы/папки игноировались во все проете (полезно для `__pycache__`)

2020-12-10 09:30 UTC, Vokler commented on geekshop/geekshop/urls.py
> +    path('new/', mainapp_views.new, name='new'),
Думаю тестовые функции ttt/ и new/ лучше удалить, оставив только products и index

2020-12-10 09:30 UTC, Vokler commented on geekshop/mainapp/views.py
>      json_products = json_from('cloth_cadrs.json')
Все, что связано с json теперь можно удалить. Данные теперь все берутся из БД

2020-12-10 09:30 UTC, Vokler commented on geekshop/requirements.txt
> +sqlparse==0.4.1
pytz и sqlparse установяться автомтически при установки Django,можно удалить

2020-12-10 12:46 UTC, Bulgakoff commented on geekshop/geekshop/urls.py
> +    path('new/', mainapp_views.new, name='new'),
тесты убрал

2020-12-10 12:46 UTC, Bulgakoff commented on .gitignore
> +.idea/
слеш убрал, __pycahce__  удалил

2020-12-10 12:46 UTC, Bulgakoff commented on geekshop/mainapp/views.py
>      json_products = json_from('cloth_cadrs.json')
json  удалил

2020-12-10 12:46 UTC, Bulgakoff commented on geekshop/requirements.txt
> +sqlparse==0.4.1
слелано

2020-12-10 15:37 UTC, Vokler approved these changes

2020-12-10 15:37 UTC, merged