geekshop/7++
Bulgakoff/BaseDjango pull request #9
Opened 2020-12-22 09:09 UTC by Bulgakoff

2020-12-26 12:12 UTC, Vokler requested changes

2020-12-26 12:12 UTC, Vokler commented on geekshop/adminapp/forms.py
> +    def __init__(self, *args, **kwargs):
Не совсем понятно, почему вы наследуетесь от UserAdminProfileForm, там же работа идет с моделью User, а тут вы форму сделали для категорий

2020-12-26 12:12 UTC, Vokler commented on geekshop/adminapp/forms.py
> +    model = ProductCategory
Тут неправильно объявляется класс. Нужно работать через Meta класс. Посмотрите на другие классы форм

2020-12-26 18:45 UTC, Bulgakoff commented on geekshop/adminapp/forms.py
> +    model = ProductCategory
вроде поправил

2020-12-26 18:48 UTC, Bulgakoff commented on geekshop/adminapp/forms.py
> +    def __init__(self, *args, **kwargs):
UserAdminProfileForm исправил, но с обновлением данных косяк у меня создается новая категория вместо редактирования и можно ли так же как пользователем не удалять совсем а делать неактивным?

2020-12-26 19:17 UTC, Vokler commented on geekshop/adminapp/forms.py
> +    def __init__(self, *args, **kwargs):
Все правильно, что создается новая. Вы ведь наследовались от CategoryAdminRegisterForm в adminapp/forms.py, а эта форма создает новые объекты. Зачем вы наследуютесь от таких форм?) Ведь каждый механизм - обнолвения, создания, удаления и тд - он индевидуален, и лучше его не пересекать с дргуим.

Да, можно сделать неактивным - просто добавьте в модель категорий новое поле is_active со значением по умолчанию True и ф-цию на удаление сделайте так, чтобы не удалялся, а просто поле is_active становилось False

2020-12-26 20:55 UTC, Bulgakoff commented on geekshop/adminapp/forms.py
> +    def __init__(self, *args, **kwargs):
готово

2020-12-27 18:55 UTC, Vokler approved these changes

2020-12-27 18:55 UTC, merged